import './coriander-lane.scss';
import { StylingConfig } from '@progress/sitefinity-nextjs-sdk/widgets/styling';

StylingConfig.OffsetClasses = {
    ...StylingConfig.OffsetClasses,
    PaddingTopNONE: '',
    PaddingTopS: 'pt-2',
    PaddingTopM: 'pt-4',
    PaddingTopL: 'pt-5',
    PaddingLeftNONE: '',
    PaddingLeftS: 'ps-2',
    PaddingLeftM: 'ps-4',
    PaddingLeftL: 'ps-5',
    PaddingBottomNONE: '',
    PaddingBottomS: 'pb-2',
    PaddingBottomM: 'pb-4',
    PaddingBottomL: 'pb-5',
    PaddingRightNONE: '',
    PaddingRightS: 'pe-2',
    PaddingRightM: 'pe-4',
    PaddingRightL: 'pe-5',
    MarginTopNONE: '',
    MarginTopS: 'mt-2',
    MarginTopM: 'mt-4',
    MarginTopL: 'mt-5',
    MarginLeftNONE: '',
    MarginLeftS: 'ms-2',
    MarginLeftM: 'ms-4',
    MarginLeftL: 'ms-5',
    MarginBottomNONE: '',
    MarginBottomS: 'mb-2',
    MarginBottomM: 'mb-4',
    MarginBottomL: 'mb-5',
    MarginRightNONE: '',
    MarginRightS: 'me-2',
    MarginRightM: 'me-4',
    MarginRightL: 'me-5',
};
